apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-go-crud-postgres-argo-deployment
spec:
  selector:
    matchLabels:
      app: myapp-go-crud-postgres-argo
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp-go-crud-postgres-argo
    spec:
      containers:
      - name: myapp-go-crud-postgres-argo
        image: satriagitu/go-crud-postgres:v1.1.2
        ports:
        - containerPort: 8080